# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  pythonapp:
    build: ./python/
    command: sh -c "sleep 5s ; python ./app.py"
    ports:
      - '5000:5000'
    depends_on:
      - mysql

  mysql:
    build: ./db/
    restart: always
    environment:
      MYSQL_DATABASE: 'penzi'
      MYSQL_ROOT_PASSWORD: '12976'
    ports:
      - '3307:3306'



